name: Weekly GitHub Activity Report
on:
  schedule:
    - cron: '0 9 * * 1' # Every Monday at 9:00 UTC
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v4
    -
      uses: actions/create-github-app-token@v2
      id: app-token
      with:
        app-id: ${{ secrets.REPO_ADMIN_READ_APP_ID }}
        private-key: ${{ secrets.REPO_ADMIN_READ_APP_PRIVATE_KEY }}
    -
      name: Fetch stats
      id: stats
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
      run: |
        GH_API="/repos/${{ github.repository }}"
        TRAFFIC_API="/repos/${{ github.repository }}/traffic/views"
        ACCEPT_HEADER="Accept: application/vnd.github+json"
        API_VERSION_HEADER="X-GitHub-Api-Version: 2022-11-28"

        repo_json=$(gh api -H "$ACCEPT_HEADER" -H "$API_VERSION_HEADER" "$GH_API")
        forks=$(echo "$repo_json" | jq .forks_count)
        watchers=$(echo "$repo_json" | jq .watchers)
        stars=$(echo "$repo_json" | jq .stargazers_count)
        visitors_json=$(gh api -H "$ACCEPT_HEADER" -H "$API_VERSION_HEADER" "$TRAFFIC_API")
        visitors=$(echo "$visitors_json" | jq .count)

        {
          echo "FORKS=${forks}"
          echo "WATCHERS=${watchers}"
          echo "STARS=${stars}"
          echo "VISITORS=${visitors}"
        } >> "$GITHUB_ENV"
    -
      name: Send Slack notification
      run: |
        payload=$(jq -n \
          --arg repo "${{ github.server_url }}/${{ github.repository }}" \
          --arg forks "$FORKS" \
          --arg watchers "$WATCHERS" \
          --arg stars "$STARS" \
          --arg visitors "$VISITORS" \
          '{
            pretext: "*📊 Weekly Open Source Activity Report*",
            author_name: "GitHub Actions",
            author_link: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            attachments: [
              {
                color: "#36a64f",
                fields: [
                  { title: "Repository", value: $repo, short: false },
                  { title: "Forks", value: $forks, short: true },
                  { title: "Watchers", value: $watchers, short: true },
                  { title: "Stars", value: $stars, short: true },
                  { title: "Visitors (14d)", value: $visitors, short: true }
                ]
              }
            ]
          }')

        curl -X POST -H 'Content-type: application/json' \
          --data "$payload" \
          ${{ secrets.SLACK_ALERTS_ENG_WEBHOOK_URL }}
