name: Test
on:
  workflow_call:
    inputs:
      sha:
        required: true
        type: string
permissions:
  contents: read
jobs:
  typescript:
    name: Typescript Compile
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha }}
      -
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      -
        run: npm install
      -
        name: Type Check (Compile) TypeScript
        run: |
          set -e
          npx tsc
          git diff
          if ! git diff --quiet; then
            echo "❌ Emitted files found, please compile your TypeScript code before submitting a PR"
            exit 1
          else
            echo "✅No files emitted"
          fi
